In [1]:
import pandas as pd
import numpy as np

In [2]:
data_preprocessed = pd.read_csv('/work/Absenteeism_preprocessed.csv')
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

### Creating the targets
We will take the median value of 'the absenteeism time in hours' and use it as a cut-off line
**np.where(condition, value if true, value if false)** checks if a condition has been satisfied and assings a value acorrdingly

In [3]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [4]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] >
         data_preprocessed['Absenteeism Time in Hours'].median(), 1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head(2)

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   

   Excessive Absenteeism  
0                      1  
1                      0

#### A comment on the targets

In [6]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [7]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the week','Daily Work Load Average','Distance to Work'],axis=1)
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

### Select the input for the regression

**DataFrame.iloc[row indices, columns indices]** Select (slices) data by position when given rows and columns wanted

In [8]:
data_with_targets.shape

(700, 12)

In [9]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [10]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

### Standardize the data

In [11]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):

    def __init__(self, columns):
        self.scaler = StandardScaler()
        self.columns = columns
        self.mean = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns],y)
        self.mean = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [12]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [13]:
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

**List comprehension** is a syntactic construct which allows us to create a list from existing list based on loops, conditionals, etc.

In [14]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [15]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [16]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [17]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1     0.182726   
1         0         0         0         0     0.182726   
2         0         0         0         1     0.182726   
3         1         0         0         0     0.182726   
4         0         0         0         1     0.182726   

   Transportation Expense       Age  Body Mass Index  Education  Children  \
0                1.005844 -0.536062         0.767431          0  0.880469   
1               -1.574681  2.130803         1.002633          0 -0.019280   
2               -0.654143  0.248310         1.002633          0 -0.919030   
3                0.854936  0.405184        -0.643782          0  0.880469   
4                1.005844 -0.536062         0.767431          0  0.880469   

       Pets  
0  0.268487  
1 -0.589690  
2 -0.589690  
3 -0.589690  
4  0.268487

In [18]:
scaled_inputs.shape

(700, 11)

### Split the data

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 176         1         0         0         0    -0.959313   
 459         1         0         0         0    -0.102784   
 384         1         0         0         0    -1.244823   
 693         1         0         0         0    -0.388293   
 349         0         0         0         1     1.610276   
 ..        ...       ...       ...       ...          ...   
 458         1         0         0         0    -0.102784   
 301         0         0         1         0     1.039256   
 291         0         0         0         1     1.039256   
 589         0         0         0         1    -1.244823   
 485         0         0         0         1     0.468236   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 176               -0.654143 -1.006686        -1.819793          1 -0.919030   
 459                0.190942  0.091435         0.532229          1 -0.019280   
 384               -0.9861

In [21]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, shuffle=20)

In [22]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [23]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)


### Logistic regression with sklearn

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

#### Training the model

In [25]:
reg = LogisticRegression()

In [26]:
reg.fit(x_train, y_train)

LogisticRegression()

In [27]:
reg.score(x_train, y_train)

0.7642857142857142

#### Manually check the accuracy

In [28]:
model_outputs = reg.predict(x_train)
model_outputs

array([1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,

In [29]:
model_outputs == y_train

array([ True, False, False,  True, False,  True,  True,  True, False,
        True,  True,  True, False,  True, False,  True,  True,  True,
       False,  True,  True,  True, False,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True, False,  True, False,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True, False, False,  True, False,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True, False,

In [30]:
np.sum(model_outputs == y_train)

428

In [31]:
model_outputs.shape[0]

560

In [32]:
np.sum(model_outputs==y_train) / model_outputs.shape[0]

0.7642857142857142

### Finding the intercept and coefficients

In [33]:
reg.intercept_

array([-1.75570764])

In [34]:
reg.coef_

array([[ 2.90885881,  0.25165187,  3.12241109,  1.0398002 , -0.00676884,
         0.61428445, -0.19398359,  0.23767023, -0.07877143,  0.3824755 ,
        -0.31220797]])

In [35]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [36]:
feature_name = unscaled_inputs.columns.values

In [37]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                 Reason_1     2.908859
1                 Reason_2     0.251652
2                 Reason_3     3.122411
3                 Reason_4     1.039800
4              Month Value    -0.006769
5   Transportation Expense     0.614284
6                      Age    -0.193984
7          Body Mass Index     0.237670
8                Education    -0.078771
9                 Children     0.382475
10                    Pets    -0.312208

In [38]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -1.755708
1                 Reason_1     2.908859
2                 Reason_2     0.251652
3                 Reason_3     3.122411
4                 Reason_4     1.039800
5              Month Value    -0.006769
6   Transportation Expense     0.614284
7                      Age    -0.193984
8          Body Mass Index     0.237670
9                Education    -0.078771
10                Children     0.382475
11                    Pets    -0.312208

#### Interpreting the coefficients 

In [39]:
summary_table['Odds ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature name  Coefficient  Odds ratio
0                Intercept    -1.755708    0.172785
1                 Reason_1     2.908859   18.335862
2                 Reason_2     0.251652    1.286148
3                 Reason_3     3.122411   22.701048
4                 Reason_4     1.039800    2.828652
5              Month Value    -0.006769    0.993254
6   Transportation Expense     0.614284    1.848334
7                      Age    -0.193984    0.823671
8          Body Mass Index     0.237670    1.268291
9                Education    -0.078771    0.924251
10                Children     0.382475    1.465909
11                    Pets    -0.312208    0.731829

In [40]:
summary_table.sort_values('Odds ratio', ascending=False)

Feature name  Coefficient  Odds ratio
3                 Reason_3     3.122411   22.701048
1                 Reason_1     2.908859   18.335862
4                 Reason_4     1.039800    2.828652
6   Transportation Expense     0.614284    1.848334
10                Children     0.382475    1.465909
2                 Reason_2     0.251652    1.286148
8          Body Mass Index     0.237670    1.268291
5              Month Value    -0.006769    0.993254
9                Education    -0.078771    0.924251
7                      Age    -0.193984    0.823671
11                    Pets    -0.312208    0.731829
0                Intercept    -1.755708    0.172785

#### Backward elimination
The idea is that we can simplify our model by removing all features which have close to no contribution to the model

When we have the p-value, we get rid of all coefficients with p-value>0.5

### Testing the model
**sklearn.linear_model.LogisticRegression.predic_proba(x)** returns the propability for all the possible outputs, the first one is the propability of being 0, the second is the propability of being 1

In [41]:
reg.score(x_test,y_test)

0.7714285714285715

In [42]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71887376, 0.28112624],
       [0.42672718, 0.57327282],
       [0.74810221, 0.25189779],
       [0.07441794, 0.92558206],
       [0.7227628 , 0.2772372 ],
       [0.7227628 , 0.2772372 ],
       [0.43193553, 0.56806447],
       [0.38988927, 0.61011073],
       [0.75100449, 0.24899551],
       [0.85660748, 0.14339252],
       [0.39172968, 0.60827032],
       [0.7227628 , 0.2772372 ],
       [0.74773785, 0.25226215],
       [0.43514623, 0.56485377],
       [0.74773785, 0.25226215],
       [0.25744393, 0.74255607],
       [0.69101047, 0.30898953],
       [0.69962711, 0.30037289],
       [0.83153963, 0.16846037],
       [0.43609649, 0.56390351],
       [0.07435761, 0.92564239],
       [0.43182409, 0.56817591],
       [0.8425018 , 0.1574982 ],
       [0.74846622, 0.25153378],
       [0.51302498, 0.48697502],
       [0.43182409, 0.56817591],
       [0.59340632, 0.40659368],
       [0.48248988, 0.51751012],
       [0.93867936, 0.06132064],
       [0.07468461, 0.92531539],
       [0.

In [43]:
predicted_proba.shape

(140, 2)

In [44]:
predicted_proba[:,1] #if the probability is: below 0.5 it places a 0, above 0.5 it places a 1

array([0.28112624, 0.57327282, 0.25189779, 0.92558206, 0.2772372 ,
       0.2772372 , 0.56806447, 0.61011073, 0.24899551, 0.14339252,
       0.60827032, 0.2772372 , 0.25226215, 0.56485377, 0.25226215,
       0.74255607, 0.30898953, 0.30037289, 0.16846037, 0.56390351,
       0.92564239, 0.56817591, 0.1574982 , 0.25153378, 0.48697502,
       0.56817591, 0.40659368, 0.51751012, 0.06132064, 0.92531539,
       0.3383343 , 0.25189779, 0.6841289 , 0.43867833, 0.25189779,
       0.68621328, 0.28073585, 0.73705433, 0.1690025 , 0.25044385,
       0.92650852, 0.40752658, 0.2486343 , 0.48697502, 0.28151697,
       0.14339252, 0.28112624, 0.33920011, 0.83514387, 0.46230526,
       0.14339252, 0.8491849 , 0.50105597, 0.73952199, 0.65801838,
       0.51557967, 0.25044385, 0.770628  , 0.25226215, 0.82411878,
       0.63251038, 0.68621328, 0.73442414, 0.8590333 , 0.40752658,
       0.49960654, 0.27840042, 0.4672536 , 0.40426439, 0.29985104,
       0.90770579, 0.12002324, 0.27762461, 0.30898953, 0.96888

### Save the model

**Pickle [module]** is a python module used to convert a python object into a character stream

In [45]:
import pickle

In [46]:
#model = file name, wb = write bytes
with open('model', 'wb') as file: 
    pickle.dump(reg, file)

In [47]:
#pickle the scaler file
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=e5a5141d-3930-4240-aa9e-425d1278178e' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>